site_name: Menagerie Guidebook
theme:
    name: flatly
    custom_dir: themes/toc_only
extra_css: css/custom.css
pages:
    - 'Introduction': 'index.md'
    - 'General Information':
        - 'Terminology': 'terminology.md'
        - 'Data Files': 'data_files.md'
        - 'Loading Mods': 'loading_mods.md'
        - 'Conditions': 'conditions.md'
    - 'Data Specifications':
        - 'Monsters': 'specs/monsters.md'
        - 'Items': 'specs/items.md'
        - 'Objects': 'specs/objects.md'
        - 'NPCs': 'specs/npcs.md'
        - 'Locations': 'specs/locations.md'
        - 'Events': 'specs/events.md'
        - 'Requests': 'specs/requests.md'
        - 'Contacts': 'specs/contacts.md'
extra_css: 
    - css/custom.css
markdown_extensions:
    - markdown.extensions.admonition
    - markdown.extensions.toc
    - markdown.extensions.meta
